config/routes.rb
Weebook::Application.routes.draw do
  resources :books
  resource :sessions
  resources :users
  root 'books#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :books
	has_secure_password


	# validates_presence_of :name, :email, :hashed_password 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include ApplicationHelper
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  respond_to :json, :html

  def index
    @books = Book.all
    respond_with @books
  end

  def new
    
    @book = current_user.Book.new
  end

  def create
    @book = Book.new(set_params)
    @book.user_id = current_user.id
    if @book.save
      respond_to do |format|
        format.html { redirect_to books_path }
        format.json { render json: @book, status: :created }
      end
    else
      respond_to do |format|
        format.html { redirect_to 'new' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
   
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update_attributes(set_params)
      respond_to do |format|
        format.html { redirect_to books_path }
        format.json { render nothing: true, status: :no_content }
      end
    else
      respond_to do |format|
        format.html { render 'edit' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    respond_to do |format|
        format.html { redirect_to :root }
        format.json { render json: {head: :ok} }
      end
  end


  protected

  def set_params
    params.require(:book).permit(:title, :author, :ISBN, :course_code)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
 def create
    @user = User.where(:email => params[:session][:email]).first

    if @user == nil || !@user.authenticate(params[:session][:password])
      flash[:error] = "Invalid email/password combination"
      render 'new'
    else
      session[:remember_token] = @user.id
      @current_user = @user
      redirect_to "/books/#/profile"
    end
  end

  def destroy
    session.delete(:remember_token)
    redirect_to "/books/#/home"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :json, :html

  # /you.json give you the current user
  # def you
  #   respond_with current_user
  # end

  def index
    @users = User.all
    respond_with @users
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:remember_token] = @user.id
      @current_user = @user
      respond_to do |format|
        format.html {redirect_to "/books/#/profile"}
        format.json {render json: @user, status: :created}
      end
    else
      respond_to do |format|
        format.html {redirect_to 'new'}
        format.json {render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user = user.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html {redirect_to "/books/#/home"}
      format.json {render json: {head: :ok}}
    end
  end

  def show
     @user = User.find(current_user)
    respond_with @user
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      respond_to do |format|
        format.html {redirect_to books_path}
        format.json {render nothing: true, status: :no_content}
      end
    else
      respond_to do |format|
        format.html {render 'edit'}
        format.json {render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

protected

  def user_params
    params.require(:user).permit(:name,:username,:email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    @current_user ||= session[:remember_token] && User.find(session[:remember_token])
  end

  def authenticate_user
    if !current_user
      flash[:danger] = "You must sign in"
      redirect_to new_sessions_path
    end
  end

  def sign_out
    session.delete(:remember_token)
    @current_user = nil
  end

  def sign_in(user)
    session[:remember_token] =user.id
    @current_user = user
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/index.html.erb
<div ng-app="weebook-app" class="container" >
    <div id="wrapper">    	

      <div ui-view>
      	UI VIEW
      </div>
    </div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<h1>Books#show</h1>
<p>Find me in app/views/books/show.html.erb</p>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Weebook</title>
  <%= stylesheet_link_tag "application"%>
  <%= javascript_include_tag "application"%>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<div class="wrapper" ng-controller="BookCtrl">
<div class="signin" id="titlesignin">
<h1>Welcome back! Sign In</h1>
<div class="signinform">
<%= form_for :session, :url => sessions_path do |f| %>
  <strong>Email:</strong> <br/><%= f.email_field :email, placeholder: 'Email'%><br/>
  <strong>Password:</strong> <br/><%= f.password_field :password,placeholder: 'Password' %><br/>
  <%= f.submit "Log In", class:"buttons btn btn-primary"%>
<% end %>
</div>
</div>

<div class="signup" >
	<h1>New to Weebooks? Make an account here</h1>
<%= form_for User.new do |f| %>
  <strong>Name:</strong><br/> <%= f.text_field :name, placeholder: 'Name' %> <br>
  <strong>Email:</strong><br/> <%= f.email_field :email, placeholder: 'Email' %> <br>
  <strong>Password:</strong><br/> <%= f.password_field :password, placeholder: 'Password' %><br>
  <strong>Confirm Password:</strong><br/> <%= f.password_field :password_confirmation, placeholder: 'Confirm Password' %><br>
  <%= f.submit "Create Account", class: "buttons btn btn-primary"%>
<% end %>
<br>
</div>

</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>